name: compress
description: test
inputs:
  dir:
    description: 'Directory'
    required: '1'

runs:
  using: "composite"
  steps:
    - run: find "${{ inputs.dir }}" -regex '.*\.\(js\|css\|svg\|html\|ttf\)$' -exec zopfli --gzip '{}' \;
      shell: bash
 
