name: phpstan
description: test
inputs:
  dir:
    description: 'Directory'
    required: '1'

runs:
  using: "composite"
  steps:
    - run: cd "${{ inputs.dir }}"
      shell: bash
    - run: ./vendor/bin/phpstan analyse
      shell: bash
